name: Verify Pull Request Labels

on: [pull_request]


jobs:
  verify_pr_labels:
    permissions: write-all
    runs-on: ubuntu-latest
    
    steps:
      - name: Verify Pull Request Labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/workflows/scripts/check_label.js');
            await script({github, context, core})
