name: Verify Pull Request Labels

on: [pull_request]

permissions: write-all
  
jobs:
  verify_pr_labels:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify Pull Request Labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CHECK_LABEL_TOKEN }}
          script: |
            const script = require('./.github/workflows/scripts/check_label.js');
            await script({github, context, core})
